language:
  - python
jobs:
  include:
    - name: "Python 3.7.0 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      script:
        - set -e  # If any of the following steps fail, just stop at that point.
        - make -C docs html  # Build the documentation.
        - pip3 install doctr
        - doctr deploy . --built-docs docs/build/html/ # Publish the documentation.
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

install:
  # The versions of pip and numpy that come pre-installed are often too old and
  # can cause problems. Upgrade them.
  - pip install --upgrade pip numpy
  - pip install wheel
  - pip install spinnaker_python-2.0.0.109-cp37-cp37m-linux_x86_64.whl
  # Install this package and the packages listed in requirements.txt.
  - pip install .
  # Install extra requirements for running tests and building docs.
  - pip install -r requirements-dev.txt

script:
#  - coverage run -m pytest  # Run the tests and check for test coverage.
#  - coverage report -m  # Generate test coverage report.
#  - codecov  # Upload the report to codecov.
  #- flake8  # Enforce code style ('relaxed' line length limit is set in .flake8 config file).
#  - make -C docs html  # Build the documentation.

notifications:
  email: false
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

env:
  global:
    # Doctr deploy key for vstadnytskyi/lcp-flir
    - secure: "BnunoyK+xJAo/774mCxpOAI4ccyS87aTix66JrIqEZ3E9E7LknXZ75U5FU5FZcO2+JkAqeemutHHIZy/fSJPBjTz839Qf/bXSEqhoa/9HTFgZF9tbIK2ALEBK31jlS6uy9KUKiek7u4OFEWNNsu1V6a61ckehF/cG11oN6V7PAhO+w2wg54NULtj0VRr2bDxfAVtnNZoWcmfSfOTdpiAEL3DjyAVpr8iPiMdv461qclJ8kmFoJIsM+tJenln5N8lvsIHwL4JG1N1qSo74aqKsKeDvjiMqdtVqGMULYYz0JxSe+Y2jbbCMiTtqGP28W7jehQj12f1/YZUthojgyofpQ7wc3M1Kb9amdwvyfilEXrddpXXMoR4uxRkE0AJgEKH+uVcdNLnrbB1XckCQ15CHgWW6tFn5KCF4FaCggqccwCHxK2hDK7J5IW0gVhvUNWg6GiVoGDrHm6pszgpj9Q/+MT9fUqTptw3SaQ5vMktg6LeIXhX1nvwBmg3Q6Wz0CBdzDJXzVdqBtRuf056nl/vY3CxKk6TVdXNKJdEwZLCFQi48hFRWSz5x3Fi6b8ecBHG7YkxDaTUpVusX+CQ1xf07p2EfL+AFsfZCeQZmEnBFrIYDYodyGxYMi8dRx1Zh6zHJ4TeSSMGnJdTqdHAJwYdv0pgVgU26vQ8lPZFH5g3nNU="
